In [91]:
from numpy import *
def loadDataSet(filename):
    fr = open(filename)
    fltLine = []
    for line in fr.readlines():
        curLine = line.strip().split('\t')
        fltLine.append(curLine)
    return mat(fltLine).astype('float64')#这里需要转换成float不然会报错

#计算两个向量的欧式距离各个树的平方和再开更更号
def distEclud(vecA,vecB):
    return sqrt(sum(power(vecA-vecB,2)))

#对于给定的数据集，创建一个包含k个随机质心的集合
def randCent(dataSet,k):
    n = shape(dataSet)[1]
    centroids = mat(zeros((k,n)))
    for j in range(n):
        minJ = min(dataSet[:,j])#每一列中的最小值
        maxJ = max(dataSet[:,j])
        rangeJ = float((maxJ - minJ)/k)
        centroids[:,j] = minJ +rangeJ*random.rand(k,1)#这里通过每一维的最大值最小值通过取值范围和最小值和差值达到数据的边界
    return centroids

def kMeans(dataSet, k, distMeas=distEclud, createCent=randCent):
    m = shape(dataSet)[0]
    clusterAssment = mat(zeros((m,2)))#create mat to assign data points 
                                      #to a centroid, also holds SE of each point
    centroids = createCent(dataSet, k)
    clusterChanged = True#标志变量为TRUE继续迭代
    while clusterChanged:
        clusterChanged = False
        for i in range(m):#对每一行的数据
            minDist = inf; minIndex = -1
            for j in range(k):#对于k列中的数据进行计算得到与中间值的欧式距离
                distJI = distMeas(centroids[j,:],dataSet[i,:])
                if distJI < minDist:
                    minDist = distJI; minIndex = j
            if clusterAssment[i,0] != minIndex: clusterChanged = True#将第每一行的最小的欧式距离存到clusterAssment
            clusterAssment[i,:] = minIndex,minDist**2
        print(centroids)
        for cent in range(k):#recalculate centroids
            ptsInClust = dataSet[nonzero(clusterAssment[:,0].A==cent)[0]]#得到集群中的所有值
            centroids[cent,:] = mean(ptsInClust, axis=0) #得到均值(列)，更新质点的位置
    return centroids, clusterAssment

In [82]:
dataSet = loadDataSet('E:/谢远东/机器学习/机器学习实践/机器学习实战源代码/machinelearninginaction/Ch10/testSet.txt')
dataSet

matrix([[ 1.658985,  4.285136],
        [-3.453687,  3.424321],
        [ 4.838138, -1.151539],
        [-5.379713, -3.362104],
        [ 0.972564,  2.924086],
        [-3.567919,  1.531611],
        [ 0.450614, -3.302219],
        [-3.487105, -1.724432],
        [ 2.668759,  1.594842],
        [-3.156485,  3.191137],
        [ 3.165506, -3.999838],
        [-2.786837, -3.099354],
        [ 4.208187,  2.984927],
        [-2.123337,  2.943366],
        [ 0.704199, -0.479481],
        [-0.39237 , -3.963704],
        [ 2.831667,  1.574018],
        [-0.790153,  3.343144],
        [ 2.943496, -3.357075],
        [-3.195883, -2.283926],
        [ 2.336445,  2.875106],
        [-1.786345,  2.554248],
        [ 2.190101, -1.90602 ],
        [-3.403367, -2.778288],
        [ 1.778124,  3.880832],
        [-1.688346,  2.230267],
        [ 2.592976, -2.054368],
        [-4.007257, -3.207066],
        [ 2.257734,  3.387564],
        [-2.679011,  0.785119],
        [ 0.939512, -4.023563],
        

In [83]:
max(mat(dataSet).astype('float64')[:,0])

matrix([[ 4.838138]])

In [84]:
max(mat(dataSet).astype('float64')[:,1])

matrix([[ 5.1904]])

In [85]:
min(mat(dataSet).astype('float64')[:,0])

matrix([[-5.379713]])

In [86]:
min(mat(dataSet).astype('float64')[:,1])

matrix([[-4.232586]])

In [87]:
randCent(dataSet,4)

matrix([[-3.89104721, -3.67655037],
        [-3.00371568, -2.09826217],
        [-5.24825284, -1.87907603],
        [-4.88085251, -3.38771386]])

In [89]:
distEclud(dataSet[0],dataSet[1])

5.184632816681332

In [96]:
centroids, clusterAssment = kMeans(dataSet,4)

[[-3.34100623 -3.52635672]
 [-3.4185104  -3.29355685]
 [-4.7758524  -2.15328971]
 [-4.38261169 -3.22764327]]
[[ 1.94170105 -3.11794914]
 [ 0.87547393  0.96629869]
 [-2.24039879  2.55469942]
 [-4.5251306  -3.2792942 ]]
[[ 2.7481024  -2.90572575]
 [ 2.53499033  2.93781533]
 [-2.46154315  2.78737555]
 [-3.53973889 -2.89384326]]
[[ 2.65077367 -2.79019029]
 [ 2.6265299   3.10868015]
 [-2.46154315  2.78737555]
 [-3.53973889 -2.89384326]]


In [100]:
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(array(centroids)[:,0],array(centroids)[:,1],c='cyan',marker='o')
ax.scatter(array(dataSet)[:,0],array(dataSet)[:,1],c='black',marker='o')
plt.show()