In [36]:
from numpy import *
def loadDataSet(filename,delim='\t'):
    stringArr = [line.strip().split(delim) for line in open(filename).readlines()]
    dataArr = [line for line in stringArr]
    return mat(dataArr).astype('float64')

def pca(dataMat,topNfeat = 9999999):
    meanVals = mean(dataMat,axis=0)
    meanRemoved = dataMat - meanVals#去平均值
    covMat = cov(meanRemoved,rowvar=0)#得到协方差矩阵
    
    eigVals,eigVects = linalg.eig(mat(covMat))#得到协方差矩阵的特征值和特征向量
    eigValInd = argsort(eigVals)#将特征值进行排序
    eigValInd = eigValInd[:-(topNfeat+1):-1]
    redBigVects = eigVects[:,eigValInd]
    lowDDataMat = meanRemoved*redBigVects
    reconMat = (lowDDataMat*redBigVects.T)+meanVals#将数据转换到新空间
    return lowDDataMat,reconMat

def replaceNanWithMean():
    dataMat = loadDataSet('E:/谢远东/机器学习/机器学习实践/机器学习实战源代码/machinelearninginaction/Ch13/secom.data',' ')
    numFeat = shape(dataMat)[1]
    for i in range(numFeat):
        meanVal = mean(dataMat[nonzero(-isnan(dataMat[:,i].A))[0],i])#去掉nan的平均值
        dataMat[nonzero(isnan(dataMat[:,i].A))[0],i] = meanVal#将所有nan设置为平均值
    return dataMat

In [24]:
dataMat = loadDataSet('E:/谢远东/机器学习/机器学习实践/机器学习实战源代码/machinelearninginaction/Ch13/testSet.txt')
lowDMat,reconMat = pca(dataMat,1)
lowDMat

matrix([[ -2.51033597e+00],
        [ -2.86915379e+00],
        [  9.74108510e-02],
        [ -7.67782222e-01],
        [  1.02715333e+00],
        [ -1.44409178e+00],
        [ -2.17360352e+00],
        [ -7.73998803e-01],
        [ -1.09983463e+00],
        [ -1.70275987e+00],
        [ -5.39605615e-01],
        [ -9.15572638e-01],
        [ -2.42669452e+00],
        [  2.93613464e+00],
        [  3.92702506e-01],
        [  2.59205734e+00],
        [  4.96435625e-01],
        [ -1.52069930e+00],
        [  1.25471104e-01],
        [  1.41846162e+00],
        [  5.89902904e-01],
        [  6.69601540e-01],
        [  3.25466068e-01],
        [  1.18812333e+00],
        [  2.07790920e+00],
        [  3.24938650e-01],
        [  3.41109884e+00],
        [  1.92249899e+00],
        [ -6.57788287e-01],
        [ -3.56836313e-01],
        [  5.72240108e-02],
        [  1.13444036e+00],
        [ -2.47196176e-01],
        [  1.14678135e+00],
        [  1.62503940e+00],
        [ -2.1148913

In [25]:
reconMat

matrix([[ 10.37044569,  11.23955536],
        [ 10.55719313,  11.54594665],
        [  9.01323877,   9.01282393],
        ..., 
        [  9.32502753,   9.52436704],
        [  9.0946364 ,   9.14637075],
        [  9.16271152,   9.2580597 ]])

In [26]:
shape(lowDMat)

(1000, 1)

In [33]:
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(dataMat[:,0].flatten().A[0],dataMat[:,1].flatten().A[0],s=90)
ax.scatter(reconMat[:,0].flatten().A[0],reconMat[:,1].flatten().A[0],s=50,c='red')
plt.show()

In [42]:
dataMat = replaceNanWithMean()
dataMat

D:\develop\Anaconda\lib\site-packages\ipykernel\__main__.py:24: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.


matrix([[  3.03093000e+03,   2.56400000e+03,   2.18773330e+03, ...,
           1.64749042e-02,   5.28333333e-03,   9.96700663e+01],
        [  3.09578000e+03,   2.46514000e+03,   2.23042220e+03, ...,
           2.01000000e-02,   6.00000000e-03,   2.08204500e+02],
        [  2.93261000e+03,   2.55994000e+03,   2.18641110e+03, ...,
           4.84000000e-02,   1.48000000e-02,   8.28602000e+01],
        ..., 
        [  2.97881000e+03,   2.37978000e+03,   2.20630000e+03, ...,
           8.60000000e-03,   2.50000000e-03,   4.35231000e+01],
        [  2.89492000e+03,   2.53201000e+03,   2.17703330e+03, ...,
           2.45000000e-02,   7.50000000e-03,   9.34941000e+01],
        [  2.94492000e+03,   2.45076000e+03,   2.19544440e+03, ...,
           1.62000000e-02,   4.50000000e-03,   1.37784400e+02]])

In [43]:
meanVals = mean(dataMat,axis=0)
meanRemoved = dataMat - meanVals
covMat = cov(meanRemoved,rowvar=0)
eigVals,eigVects = linalg.eig(mat(covMat))
eigVals

array([  5.34151979e+07,   2.17466719e+07,   8.24837662e+06,
         2.07388086e+06,   1.31540439e+06,   4.67693557e+05,
         2.90863555e+05,   2.83668601e+05,   2.37155830e+05,
         2.08513836e+05,   1.96098849e+05,   1.86856549e+05,
         1.52422354e+05,   1.13215032e+05,   1.08493848e+05,
         1.02849533e+05,   1.00166164e+05,   8.33473762e+04,
         8.15850591e+04,   7.76560524e+04,   6.66060410e+04,
         6.52620058e+04,   5.96776503e+04,   5.16269933e+04,
         5.03324580e+04,   4.54661746e+04,   4.41914029e+04,
         4.15532551e+04,   3.55294040e+04,   3.31436743e+04,
         2.67385181e+04,   1.47123429e+04,   1.44089194e+04,
         1.09321187e+04,   1.04841308e+04,   9.48876548e+03,
         8.34665462e+03,   7.22765535e+03,   5.34196392e+03,
         4.95614671e+03,   4.23060022e+03,   4.10673182e+03,
         3.41199406e+03,   3.24193522e+03,   2.74523635e+03,
         2.35027999e+03,   2.16835314e+03,   1.86414157e+03,
         1.76741826e+03,

In [41]:
eigVects

matrix([[-0.85389096, -0.52045195],
        [ 0.52045195, -0.85389096]])