In [79]:
from numpy import *
def loadDataSet(filename):
    numFeat = len(open(filename).readline().strip().split('\t')) - 1
    dataMat = []; labelMat = []
    fr = open(filename)
    for line in fr.readlines():
        lineArr = []
        curLine = line.strip().split('\t')
        for i in range(numFeat):
            lineArr.append(float(curLine[i]))
        dataMat.append(lineArr)
        labelMat.append(float(curLine[-1]))
    return dataMat,labelMat

def standRegres(xArr,yArr):
    xMat = mat(xArr);yMat = mat(yArr).T
    xTx = xMat.T*xMat
    if linalg.det(xTx) == 0.0:#求行列式如果为0的话为奇异矩阵
        print("这个矩阵是奇异矩阵，不可逆")
        return
    ws = xTx.I * (xMat.T*yMat)
    return ws

def lwlr(testPoint,xArr,yArr,k=1.0):
    xMat = mat(xArr);yMat = mat(yArr).T
    m = shape(xMat)[0]
    weights = mat(eye(m))#构建对角矩阵
    for j in range(m):
        diffMat = testPoint - xMat[j,:]
        weights[j,j] = exp(diffMat*diffMat.T/(-2.0*k**2))
    xTx = xMat.T*(weights * xMat)
    if linalg.det(xTx) == 0.0:
        print("这个矩阵是奇异矩阵，不可逆")
        return
    ws = xTx.I *(xMat.T*(weights*yMat))
    return testPoint*ws

def lwlrTest(testArr,xArr,yArr,k=1.0):
    m = shape(testArr)[0]
    yHat = zeros(m)
    for i in range(m):
        yHat[i] = lwlr(testArr[i],xArr,yArr,k)
    return yHat

def rssError(yArr,yHatArr):
    return ((yArr-yHatArr)**2).sum()

def stageWise(xArr,yArr,eps=0.01,numIt =100):#步长和迭代数
    xMAt = mat(xArr);yMat = mat(yArr)
    yMean = mean(yMat,0)
    yMat = yMat -yMean
    xMat = regularize(xMat)
    m,n = shape(xMat)
    returnMat = zeros((numIt,n))
    ws = zeros((n,1));wsTest = ws.copy();wsMax=ws.copy()
    for i in range(numIt):
        print(ws.T)
        lowestError = inf; 
        for j in range(n):
            for sign in [-1,1]:
                wsTest = ws.copy()
                wsTest[j] += eps*sign
                yTest = xMat*wsTest
                rssE = rssError(yMat.A,yTest.A)
                if rssE < lowestError:
                    lowestError = rssE
                    wsMax = wsTest
        ws = wsMax.copy()
        returnMat[i,:] = ws.T
    return returnMat

In [2]:
xArr,yArr = loadDataSet('E:/谢远东/机器学习/机器学习实践/机器学习实战源代码/machinelearninginaction/Ch08/ex0.txt')
xArr

[[1.0, 0.067732],
 [1.0, 0.42781],
 [1.0, 0.995731],
 [1.0, 0.738336],
 [1.0, 0.981083],
 [1.0, 0.526171],
 [1.0, 0.378887],
 [1.0, 0.033859],
 [1.0, 0.132791],
 [1.0, 0.138306],
 [1.0, 0.247809],
 [1.0, 0.64827],
 [1.0, 0.731209],
 [1.0, 0.236833],
 [1.0, 0.969788],
 [1.0, 0.607492],
 [1.0, 0.358622],
 [1.0, 0.147846],
 [1.0, 0.63782],
 [1.0, 0.230372],
 [1.0, 0.070237],
 [1.0, 0.067154],
 [1.0, 0.925577],
 [1.0, 0.717733],
 [1.0, 0.015371],
 [1.0, 0.33507],
 [1.0, 0.040486],
 [1.0, 0.212575],
 [1.0, 0.617218],
 [1.0, 0.541196],
 [1.0, 0.045353],
 [1.0, 0.126762],
 [1.0, 0.556486],
 [1.0, 0.901144],
 [1.0, 0.958476],
 [1.0, 0.274561],
 [1.0, 0.394396],
 [1.0, 0.87248],
 [1.0, 0.409932],
 [1.0, 0.908969],
 [1.0, 0.166819],
 [1.0, 0.665016],
 [1.0, 0.263727],
 [1.0, 0.231214],
 [1.0, 0.552928],
 [1.0, 0.047744],
 [1.0, 0.365746],
 [1.0, 0.495002],
 [1.0, 0.493466],
 [1.0, 0.792101],
 [1.0, 0.76966],
 [1.0, 0.251821],
 [1.0, 0.181951],
 [1.0, 0.808177],
 [1.0, 0.334116],
 [1.0, 0.33863],

In [3]:
yArr

[3.176513,
 3.816464,
 4.550095,
 4.256571,
 4.560815,
 3.929515,
 3.52617,
 3.156393,
 3.110301,
 3.149813,
 3.476346,
 4.119688,
 4.282233,
 3.486582,
 4.655492,
 3.965162,
 3.5149,
 3.125947,
 4.094115,
 3.476039,
 3.21061,
 3.190612,
 4.631504,
 4.29589,
 3.085028,
 3.44808,
 3.16744,
 3.364266,
 3.993482,
 3.891471,
 3.143259,
 3.114204,
 3.851484,
 4.621899,
 4.580768,
 3.620992,
 3.580501,
 4.618706,
 3.676867,
 4.641845,
 3.175939,
 4.26498,
 3.558448,
 3.436632,
 3.831052,
 3.182853,
 3.498906,
 3.946833,
 3.900583,
 4.238522,
 4.23308,
 3.521557,
 3.203344,
 4.278105,
 3.555705,
 3.502661,
 3.859776,
 4.275956,
 3.916191,
 3.587961,
 3.183004,
 4.225236,
 4.231083,
 4.240544,
 3.222372,
 4.021445,
 3.567479,
 3.56258,
 4.262059,
 3.208813,
 3.169825,
 4.193949,
 3.491678,
 4.533306,
 3.550108,
 4.636427,
 3.557078,
 3.552874,
 3.494159,
 3.206828,
 3.195266,
 4.221292,
 4.413372,
 4.184347,
 3.742878,
 3.201878,
 4.648964,
 3.510117,
 3.274434,
 3.579622,
 3.489244,
 4.237386

In [4]:
ws = standRegres(xArr,yArr)
ws

matrix([[ 3.00774324],
        [ 1.69532264]])

In [5]:
xMat = mat(xArr)
yMat = mat(yArr)
yHat = xMat*ws
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(xMat[:,1].flatten().A[0],yMat.T[:,0].flatten().A[0])#flatten将矩阵压扁，例如mat([[1,3],[2,4],[3,5]]).flatten = matrix([1, 3, 2, 4, 3, 5]),还可以用于数组但是在列表中的时候[y for x in a for y in x]才能将列表a压扁 
ax.plot(xMat[:,1],yHat)


In [6]:
xCopy = xMat.copy()
xCopy.sort()
yHat = xCopy*ws
ax.plot(xCopy[:,1],yHat)
plt.show()

In [7]:
corrcoef(yHat.T,yMat)

array([[ 1.        ,  0.98647356],
       [ 0.98647356,  1.        ]])

In [15]:
xArr,yArr = loadDataSet('E:/谢远东/机器学习/机器学习实践/机器学习实战源代码/machinelearninginaction/Ch08/ex0.txt')
yArr[0]

3.176513

In [16]:
xArr

[[1.0, 0.067732],
 [1.0, 0.42781],
 [1.0, 0.995731],
 [1.0, 0.738336],
 [1.0, 0.981083],
 [1.0, 0.526171],
 [1.0, 0.378887],
 [1.0, 0.033859],
 [1.0, 0.132791],
 [1.0, 0.138306],
 [1.0, 0.247809],
 [1.0, 0.64827],
 [1.0, 0.731209],
 [1.0, 0.236833],
 [1.0, 0.969788],
 [1.0, 0.607492],
 [1.0, 0.358622],
 [1.0, 0.147846],
 [1.0, 0.63782],
 [1.0, 0.230372],
 [1.0, 0.070237],
 [1.0, 0.067154],
 [1.0, 0.925577],
 [1.0, 0.717733],
 [1.0, 0.015371],
 [1.0, 0.33507],
 [1.0, 0.040486],
 [1.0, 0.212575],
 [1.0, 0.617218],
 [1.0, 0.541196],
 [1.0, 0.045353],
 [1.0, 0.126762],
 [1.0, 0.556486],
 [1.0, 0.901144],
 [1.0, 0.958476],
 [1.0, 0.274561],
 [1.0, 0.394396],
 [1.0, 0.87248],
 [1.0, 0.409932],
 [1.0, 0.908969],
 [1.0, 0.166819],
 [1.0, 0.665016],
 [1.0, 0.263727],
 [1.0, 0.231214],
 [1.0, 0.552928],
 [1.0, 0.047744],
 [1.0, 0.365746],
 [1.0, 0.495002],
 [1.0, 0.493466],
 [1.0, 0.792101],
 [1.0, 0.76966],
 [1.0, 0.251821],
 [1.0, 0.181951],
 [1.0, 0.808177],
 [1.0, 0.334116],
 [1.0, 0.33863],

In [9]:
lwlr(xArr[0],xArr,yArr,1.0)

matrix([[ 3.12204471]])

In [29]:
yHat = lwlrTest(xArr,xArr,yArr,0.003)
yHat

matrix([[ 3.20200665],
        [ 3.75940186],
        [ 4.53670134],
        [ 4.25050564],
        [ 4.56094936],
        [ 3.93721635],
        [ 3.53392289],
        [ 3.15405352],
        [ 3.12604366],
        [ 3.14881027],
        [ 3.47887849],
        [ 4.1229893 ],
        [ 4.24110737],
        [ 3.47648492],
        [ 4.6329319 ],
        [ 3.96601531],
        [ 3.52772681],
        [ 3.15257242],
        [ 4.09411431],
        [ 3.4534635 ],
        [ 3.21009102],
        [ 3.19948401],
        [ 4.63028986],
        [ 4.2958291 ],
        [ 3.08502796],
        [ 3.50177161],
        [ 3.14348409],
        [ 3.36386424],
        [ 3.99136073],
        [ 3.89052382],
        [ 3.15925294],
        [ 3.15754913],
        [ 3.85062092],
        [ 4.63492639],
        [ 4.56823397],
        [ 3.59158542],
        [ 3.59663089],
        [ 4.60657847],
        [ 3.6768816 ],
        [ 4.64165521],
        [ 3.18193434],
        [ 4.23203805],
        [ 3.5596501 ],
        [ 3

In [30]:
#对xArr排序
xMat=mat(xArr)
yMat=mat(yArr)
srtInd = xMat[:,1].argsort(0)
xSort=xMat[srtInd][:,0,:] 
import matplotlib.pyplot as plt
fig=plt.figure()
ax=fig.add_subplot(111)
ax.scatter(xMat[:,1].flatten().A[0],yMat.T[:,0].flatten().A[0],s=2,c='red')
ax.plot(xSort[:,1],yHat[srtInd][:,0,:])
plt.show()

In [51]:
abX,abY = loadDataSet('E:/谢远东/机器学习/机器学习实践/机器学习实战源代码/machinelearninginaction/Ch08/abalone.txt')
yHat01 = lwlrTest(abX[0:99],abX[0:99],abY[0:99],0.1)
yHat1 = lwlrTest(abX[0:99],abX[0:99],abY[0:99],1)
yHat10 = lwlrTest(abX[0:99],abX[0:99],abY[0:99],10)

error01 = rssError(abY[0:99],array(yHat01.T))
error1 = rssError(abY[0:99],yHat1.T)
error10 = rssError(abY[0:99],yHat10.T)

error01,error1,error10

(56.804197255611498, 429.8905618702197, 549.11817088267856)

In [54]:
yHat011 = lwlrTest(abX[100:199],abX[0:99],abY[0:99],0.1)
yHat11 = lwlrTest(abX[100:199],abX[0:99],abY[0:99],1)
yHat101 = lwlrTest(abX[100:199],abX[0:99],abY[0:99],10)

error011 = rssError(abY[100:199],array(yHat011.T))
error11 = rssError(abY[100:199],yHat11.T)
error101 = rssError(abY[100:199],yHat101.T)

error011,error11,error101

(106085.40657203968, 573.5261441895799, 517.57119053828137)

In [59]:
ws = standRegres(abX[0:99],abY[0:99])
yHat = mat(abX[100:199])*ws
errorstand = rssError(abY[100:199],yHat.T.A)
errorstand

518.63631532464444

In [74]:
ridgeWeights = ridgeTest(abX,abY)
ridgeWeights

array([[  4.30441949e-02,  -2.27416346e-02,   1.32140875e-01,
          2.07518171e-02,   2.22403745e+00,  -9.98952980e-01,
         -1.17254237e-01,   1.66229222e-01],
       [  4.30441928e-02,  -2.27416370e-02,   1.32140878e-01,
          2.07518175e-02,   2.22403626e+00,  -9.98952746e-01,
         -1.17254174e-01,   1.66229339e-01],
       [  4.30441874e-02,  -2.27416435e-02,   1.32140885e-01,
          2.07518187e-02,   2.22403305e+00,  -9.98952110e-01,
         -1.17254003e-01,   1.66229656e-01],
       [  4.30441725e-02,  -2.27416613e-02,   1.32140904e-01,
          2.07518218e-02,   2.22402431e+00,  -9.98950381e-01,
         -1.17253537e-01,   1.66230518e-01],
       [  4.30441321e-02,  -2.27417096e-02,   1.32140956e-01,
          2.07518304e-02,   2.22400054e+00,  -9.98945682e-01,
         -1.17252271e-01,   1.66232862e-01],
       [  4.30440221e-02,  -2.27418409e-02,   1.32141096e-01,
          2.07518537e-02,   2.22393595e+00,  -9.98932910e-01,
         -1.17248829e-01,   1.6

In [75]:
import matplotlib.pyplot as plt
fig=plt.figure()
ax=fig.add_subplot(111)
ax.plot(ridgeWeights)
plt.show()